### ISSUE TITLE
 Weird Crash

### ISSUE THREAD

**Issue by nasirky** [Usercentrics/flutter-sdk#21]
**Describe the bug**
Some of our users are facing a weird crash. We have already updated to the latest SDK but the issue is still there.

<img width="1173" alt="screenshot" src="https://user-images.githubusercontent.com/19976389/172599723-b8aa6927-ab85-4824-98d2-0f8f28f3d189.png">

**Expected behavior**
The users don't experience any crash

**Comment by uc-nfdz** [comment]
@nasirky Sorry but we have not been able to reproduce the crash. Please, provide some snippets of how you have the integration, and more information about the crash (OS, devices, versions, etc). Thanks!

**Comment by uc-nfdz** [comment]
@nasirky Please update to the latest version `2.6.1`. We have fixed some stability and fatal crash issues that may be related.
