### ISSUE TITLE
[BUG] Incorrect Dart requirement in README

### ISSUE THREAD

**Issue by molundb** [Usercentrics/flutter-sdk#31]
**Describe the bug**
The README says a requirement is Dart 2.12 or higher, but when cloning project and running `flutter pub get` the error says `usercentrics_sdk requires SDK version >=2.17.1 <3.0.0`

**To Reproduce**
1. Close project
2. Run `flutter pub get`
3. See error

**Expected behavior**
Update README to accurately reflect the requirements.

**Screenshots**
![image](https://user-images.githubusercontent.com/49907258/196427545-67f02809-dc85-4763-aad5-31e9cc019246.png)

**Flutter doctor**

```
[✓] Flutter (Channel unknown, 2.10.2, on macOS 12.6 21G115 darwin-arm, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[!] Android Studio
    ✗ Unable to find bundled Java version.
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Community Edition (version 2019.3.4)
[✓] VS Code (version 1.72.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```

**Comment by uc-leo** [comment]
thanks @molundb!
