### ISSUE TITLE
[BUG] ClassNotFoundException: com.mediatek.cta.CtaUtils

### ISSUE THREAD

**Issue by tayseer9** [Usercentrics/flutter-sdk#32]
**Describe the bug**
I'm trying to show Usercentrics sheet before running the app as follow:
```
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // init Usercentrics
  Usercentrics.initialize(
      settingsId: 'SETTINGS_ID',
      networkMode: NetworkMode.eu,
    );

   // show first layer 
   final response = await Usercentrics.showFirstLayer(
        layout: UsercentricsLayout.sheet,
        firstLayerSettings: _firstLayerSettings,
        secondLayerSettings: _secondLayerSettings,
        generalStyleSettings: _generalSettings,
      );

  // run the app
  runApp(MyApp());
}
```

After running the app, a white screen appears (**only** on Android). The log shows an exception when Usercentrics is trying to establish a connection. Therefore, the app is getting freezes before running the `MyApp` which explains the white screen.

**log**
> I/System.out(29376): [okhttp]:check permission begin!
> W/System  (29376): ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
> I/System.out(29376): [okhttp] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils

**Flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-arm, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.72.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

• No issues found!

**Device**
Xiaomi note 8 pro

**Android version**
Android 10

**Comment by uc-nfdz** [comment]
Hello @tayseer9! Thank you for opening this issue. 
What makes you think that our SDK is causing this problem? Does adding/removing our SDK make the problem appear/disappear?
This type of problem is usually related to the Flutter framework (+ very specific android devices/versions). Searching in Google I saw that it appears in other frameworks such as Ionic.

**Comment by tayseer9** [comment]
Thank you for your response, and sorry for the late reply. 
The only correlation with this issue is when trying to show the Usercentrics sheet before calling the `run()` method. 
I understand that this type of problem is usually related to the Flutter framework. I will close the issue until I find more evidence.
Meanwhile, I had to create a custom UI to avoid showing the package's sheet UI.
