### ISSUE TITLE
Release 2.7.5 not available on pub.dev

### ISSUE THREAD

**Issue by freewheelnat** [Usercentrics/flutter-sdk#37]
I see release tag for `2.7.5` in your repo and your doc recommends using `2.7.5` on native Android and iOS. However, the most recent release available on `pub.dev` is `2.7.4`.

Could you release `2.7.5` to `pub.dev` please, or let us know why it's not released yet (eg you face some stability issues with it), thanks.

**Comment by userCTest** [comment]
Hi @freewheelnat ,

thanks a lot for spotting that!
We will look into it and let you know as soon as 2.7.5 becomes available on pub.dev.

Cheers,
Rui

**Comment by userCTest** [comment]
Hey @freewheelnat 

2.7.5 is now in `pub.dev`!
If you have any further issues or suggestions, just let us know.

Cheers,
Rui
