### ISSUE TITLE
Usercentric custom UI issue (iOS)

### ISSUE THREAD

**Issue by bahag-roostap** [Usercentrics/flutter-sdk#41]
**Describe the bug**
recently in our team, we started to build our custom UI for the user-consent using the SDK in flutter, but when we want to render the widgets based on the cmpData of the UserCentric, **just in iOS** the format of the data is wrong, the category object holds a description field which should contain a simple text but in this case, is like the image below:

<img width="986" alt="CleanShot 2022-12-28 at 10 47 26@2x" src="https://user-images.githubusercontent.com/112619712/209793504-32803e53-fa7f-45f7-9fca-a98f2a609612.png">

**To Reproduce**
1. use the Usercentric to implement a simple custom UI on iOS
2. check the category object-> description field

I would appreciate it if you take a look and see what could be wrong.

**Comment by userCTest** [comment]
hi @bahag-roostap 

sorry for the delay in answering.

we have just released a new version (2.7.10) of the SDK that solves this issue.
Could you please try it out and see if things are working as expected? 
If not, please do let us know so we can have a look.

Thanks!

**Comment by bahag-roostap** [comment]
Thanks for the response, I'll check and let you know ASAP :-)
