### ISSUE TITLE
[BUG] TCFVendor.consent always null on iOS

### ISSUE THREAD

**Issue by Tassiroo** [Usercentrics/flutter-sdk#44]
**Describe the bug**
On iOS when I call `Usercentrics.tcfData` all `TCFVendor` instances in the returned `TCFData` have `consent` set to `null`. It does not matter whether the user accepted or declined consent for the vendors. This happens also in the latest version (2.7.12). On Android the values are set correctly.

**To Reproduce**
1. Initialize Usercentrics
2. Collect consent e.g. by calling `Usercentrics.showFirstLayer()`
3. Accept or decline consent
4. Retrieve `TCFData` by calling `Usercentrics.tcfData`
5. Every `TCFVendor.consent` is `null`

**Expected behavior**
`TCFVendor.consent` should be set according to the user’s choice.

**Screenshots**
<img width="591" alt="Bildschirm­foto 2023-02-16 um 11 26 08" src="https://user-images.githubusercontent.com/32636655/219344798-8ea401d9-d689-43ef-8b45-3bc5fa21020b.png">

**Comment by uc-leo** [comment]
Hi @Tassiroo, we are releasing 2.7.13 and it should fix the problem. If anything unexpected happens, please, let us know!

**Comment by Tassiroo** [comment]
Works like a charm. Thank you!
