### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by alirezat66** [Usercentrics/flutter-sdk#58]
**Describe the bug**
When the user installed app from the stores banner shows
if the user uninstall the app and install it again from the store he/she never see again the banner
**To Reproduce**
1. install an app that use the usercentrics in it
2. open it
3. see the banner
4. uninstall it
5. install it again from store
6. you can't see the usercentrics banner

**Expected behavior**
User should be see the user centrics banner in first installation of app.

**Screenshots**
unrelated
**Flutter doctor**
unrelated
**usercentrics-flutter-sdk branch/commit**
- Your fork/commit:

**Additional context**

**Comment by uc-leo** [comment]
hi @alirezat66 ,

can you provide a video evidence of this problem?

thanks

**Comment by alirezat66** [comment]
https://github.com/Usercentrics/flutter-sdk/assets/6933305/01d2d725-cdde-4953-b546-f1bec761c41d

Here is the video also you can test it directly by [installing app](https://play.google.com/store/search?q=moebel.de&c=apps&gl=DE)

**Comment by uc-leo** [comment]
hey @alirezat66 ,

thanks for the video! this looks like your app + phone is syncing application files in your google account, therefore what you see is a backup being download whenever you reinstall the app.

you can read it more about it here: https://developer.android.com/guide/topics/data/autobackup

**Comment by alirezat66** [comment]
Hi, Based on the link I guess I should set allowBackup=false in my code to solve the problem?

**Comment by uc-leo** [comment]
yes, that would be an option
