### ISSUE TITLE
[BUG] Usercentrics SDK incompatible with AGP 8

### ISSUE THREAD

**Issue by dangerground** [Usercentrics/flutter-sdk#70]
**Describe the bug**
Projects with `com.android.tools.build:gradle:8.1.0` can't be build.

```
 Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':usercentrics_sdk'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.
```

**To Reproduce**
1. `flutter create test`
2. `flutter pub add usercentrics_sdk`
3. Open Subfolder `test/android` in Android Studio
4. Run `Tools/AGP Upgrade Assisent` and Use e.g. `8.1.0` and click `Run selected steps`
5. `flutter build apk`
6. See error

**Expected behavior**
My assumption is that it should work with the latest AGP

**Flutter doctor**
```
[✓] Flutter (Channel stable, 3.13.9, on macOS 13.6 22G120 darwin-arm64, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
[✓] Connected device (4 available)
[✓] Network resources
```

**Additional context**
Maybe helpfull commit in another flutter lib https://github.com/adaptant-labs/flutter_windowmanager/pull/32/files

**Comment by uc-leo** [comment]
hi @dangerground , thanks for flagging this!

we are not supporting Gradle 8 at this moment, sorry to inform you about that.

**Comment by dangerground** [comment]
Hi @uc-leo in version 2.11.0 the issue still is present, was this closed by accident? Or is this a wontfix?

**Comment by uc-leo** [comment]
hi @dangerground , 

we closed because we already have our own issue tracker and since this is already an item on our list, we decided to not leave duplicated in here.

when we release, it will be present on our CHANGELOG. does it sounds good to you?

and thanks for the feedback!

**Comment by dangerground** [comment]
@uc-leo yes, this sounds good. I didn't know about an internal issue tracker, so I simply was confused about the implication of the closed issue.
