### ISSUE TITLE
[BUG] AdditionalConsentModeData / AdTechProvider not listed in model.dart 

### ISSUE THREAD

**Issue by abelokon0711** [Usercentrics/flutter-sdk#76]
**Describe the bug**
We don't have access to `AdditionalConsentModeData` or `AdTechProvider` since they are not listed in `model.dart` as the other classes are.

**To Reproduce**
Try to import either class in a project using this plugin.

**Additional context**
Version 2.11.0

**Comment by uc-piotukh** [comment]
Hey @abelokon0711 
Looking into this, thanks for flagging!

**Comment by uc-leo** [comment]
hey @abelokon0711 

thanks again for reporting this issue!

you may find the fix in our latest release: `2.11.1`
